const data = {
  products: [
    {
      _id: '1',
      name: 'ASUS TUF Gaming GeForce GTX 1660 Ti EVO TOP Edition 6GB GDDR6 Graphics Card',
      slug: 'ASUS GTX 1660 Ti Graphics Card',
      category: 'Graphics Card',
      image: '/images/p1.jpg',
      price: 450,
      countInStock: 10,
      brand: 'Asus',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Products',
    },
    {
      _id: '2',
      name: 'AMD Ryzen 5 5600G Processor with Radeon Graphics (Chinese Edition)',
      slug: 'AMD Ryzen 5 5600G',
      category: 'Processor',
      image: '/images/p2.jpg',
      price: 122,
      countInStock: 7,
      brand: 'AMD',
      rating: 4.8,
      numReviews: 19,
      description: 'High Quality Products',
    },
    {
      _id: '3',
      name: 'Samsung 970 EVO Plus 1TB NVMe M.2 SSD',
      slug: 'Samsung 970 1TB NVMe',
      category: 'SSD',
      image: '/images/p3.jpg',
      price: 90,
      countInStock: 12,
      brand: 'Samsung',
      rating: 4.7,
      numReviews: 11,
      description: 'High Quality Products',
    },
  ],
};

export default data;
